version: '3'
networks:
  testewp: null
services:
  web-testewp:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      ALLOW_OVERRIDE: 'true'
      DEBUG: 'true'
    container_name: web-testewp
    ports:
      - '80:80'
    networks:
      - testewp
    depends_on:
      - mysql-testewp
    volumes:
      - './www:/var/www/html/'
      - './php.ini:/usr/local/etc/php/php.ini'
  mysql-testewp:
    image: mysql
    command: '--default-authentication-plugin=mysql_native_password'
    container_name: mysql-testewp
    tty: true
    volumes:
      - './dump:/docker-entrypoint-initdb.d'
      - './data:/var/lib/mysql'
    networks:
      - testewp
    restart: unless-stopped
    environment:
      MYSQL_USER: homestead
      MYSQL_DATABASE: homestead
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_HOST: localhost
      SERVICE_TAGS: dev
      SERVICE_NAME: mysql
    ports:
      - '3306:3306'